
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import bot.penguee.Position;
import bot.penguee.fragments.Frag;
import bot.penguee.screen.cpu.Screen;
import org.junit.Test;

import java.awt.*;
import java.awt.image.BufferedImage;

import static org.junit.Assert.*;

public class TestScreen {
	@Test
	public void testGrabFind() {
		Screen screen = new Screen(false);
		try {
			screen.grab();

			BufferedImage bf = screen.getImage();
			Frag fragment = new Frag(copyImage(bf.getSubimage(50, 50, 40, 60)));

			Position mp = screen.find(fragment);
			assertNotNull(mp);
			assertEquals(mp.x, 70);
			assertEquals(mp.y, 80);

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			fail();
		}
	}

	@Test
	public void testGrabFindRect() {
		Screen screen = new Screen(false);
		try {
			screen.grab();

			BufferedImage bf = screen.getImage();
			Frag fragment = new Frag(copyImage(bf.getSubimage(50, 50, 40, 60)));
			screen.setSearchRect(0, 0, 200, 200);
			Position mp = screen.find(fragment);
			assertNotNull(mp);
			assertEquals(mp.x, 70);
			assertEquals(mp.y, 80);

			screen.setSearchRect(200, 200, 400, 400);
			Position mp2 = screen.find(fragment);
			assertNull(mp2);

			screen.setSearchRect();
			Position mp3 = screen.find(fragment);
			assertNotNull(mp);
			assertEquals(mp.x, 70);
			assertEquals(mp.y, 80);


		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			fail();
		}
	}

	private BufferedImage copyImage(BufferedImage source) {
		BufferedImage b = new BufferedImage(source.getWidth(), source.getHeight(), source.getType());
		Graphics g = b.getGraphics();
		g.drawImage(source, 0, 0, null);
		g.dispose();
		return b;
	}

}
